server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: comanda
          uri: lb://comanda
          predicates:
          - Path=/comanda/**
        - id: pet
          uri: lb://pet
          predicates:
          - Path=/pet/**
        - id: procedimento
          uri: lb://procedimento
          predicates:
          - Path=/procedimento/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.17:8761/eureka/
